/** Built-in Other World Thread theme tokens derived from the DSH visual study. */

/** Persisted id of the built-in Other World Thread theme. */
export const OTHER_WORLD_THEME_ID = 'other-world' as const

/**
 * Alias-token overrides for the built-in Other World Thread theme. The theme
 * builds on the dark base palette and maps semantic roles to the static values
 * in `styles/other-world.css`, keeping feature CSS free of palette literals and
 * theme selectors.
 */
export const OTHER_WORLD_THEME_TOKENS = Object.freeze({
  '--dsw-alias-bg-base': 'var(--dsw-static-other-world-canvas)',
  '--dsw-alias-bg-layer-1': 'var(--dsw-static-other-world-surface)',
  '--dsw-alias-bg-layer-2': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-bg-layer-3': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-bg-module-platform': 'var(--dsw-static-other-world-surface)',
  '--dsw-alias-bg-multi-select': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-bg-overlay': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-bg-skeleton': 'var(--dsw-static-other-world-cyan-08)',
  '--dsw-alias-border-l1': 'var(--dsw-static-other-world-stitch-22)',
  '--dsw-alias-border-l2-darkmode-thin': 'var(--dsw-static-other-world-stitch-34)',
  '--dsw-alias-border-l2': 'var(--dsw-static-other-world-border)',
  '--dsw-alias-border-l3': 'var(--dsw-static-other-world-focus)',
  '--dsw-alias-border-l4': 'var(--dsw-static-other-world-stitch)',
  '--dsw-alias-brand-primary-invert': 'var(--dsw-static-other-world-cream)',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': 'var(--dsw-static-other-world-orange)',
  '--dsw-alias-brand-primary': 'var(--dsw-static-other-world-orange)',
  '--dsw-alias-brand-text': 'var(--dsw-static-other-world-cream)',
  '--dsw-alias-button-contrast-fill': 'var(--dsw-static-other-world-cream)',
  '--dsw-alias-button-elevated-fill': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-button-floating-fill': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-button-floating-hover': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-button-ghost-active-border': 'var(--dsw-static-other-world-stitch)',
  '--dsw-alias-button-ghost-active-fill': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-button-ghost-active-hover': 'var(--dsw-static-other-world-elevated-2)',
  '--dsw-alias-button-info-fill': 'var(--dsw-static-other-world-cyan-strong)',
  '--dsw-alias-button-info-hover': 'var(--dsw-static-other-world-cyan)',
  '--dsw-alias-button-primary-dimmed': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-button-primary-fill': 'var(--dsw-static-other-world-orange)',
  '--dsw-alias-button-primary-hover': 'var(--dsw-static-other-world-orange-hover)',
  '--dsw-alias-interactive-bg-active': 'var(--dsw-static-other-world-orange-12)',
  '--dsw-alias-interactive-bg-hover-accent': 'var(--dsw-static-other-world-cyan-14)',
  '--dsw-alias-interactive-bg-hover-danger': 'var(--dsw-static-other-world-error-12)',
  '--dsw-alias-interactive-bg-hover-solid': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-interactive-bg-hover': 'var(--dsw-static-other-world-cyan-08)',
  '--dsw-alias-label-caption': 'var(--dsw-static-other-world-text-tertiary)',
  '--dsw-alias-label-dimmed': 'var(--dsw-static-other-world-stitch)',
  '--dsw-alias-label-primary-bluish': 'var(--dsw-static-other-world-cyan)',
  '--dsw-alias-label-primary-dimmed': 'var(--dsw-static-other-world-text-secondary)',
  '--dsw-alias-label-primary-foreground': 'var(--dsw-static-other-world-white)',
  '--dsw-alias-label-primary-inverted': 'var(--dsw-static-other-world-canvas)',
  '--dsw-alias-label-primary': 'var(--dsw-static-other-world-white)',
  '--dsw-alias-label-secondary': 'var(--dsw-static-other-world-text-secondary)',
  '--dsw-alias-label-tertiary': 'var(--dsw-static-other-world-text-tertiary)',
  '--dsw-alias-markdown-citation': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-markdown-code-block-banner': 'var(--dsw-static-other-world-surface)',
  '--dsw-alias-markdown-code-block': 'var(--dsw-static-other-world-black)',
  '--dsw-alias-markdown-code-segment-selected': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-markdown-code-segment-unselected': 'var(--dsw-static-other-world-surface)',
  '--dsw-alias-markdown-inline-code': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-markdown-placeholder': 'var(--dsw-static-other-world-surface)',
  '--dsw-alias-markdown-tag': 'var(--dsw-static-other-world-raised)',
  '--dsw-alias-scrollbar-bg-l1': 'var(--dsw-static-other-world-border)',
  '--dsw-alias-scrollbar-bg-l2': 'var(--dsw-static-other-world-focus)',
  '--dsw-alias-scrollbar-hover-l1': 'var(--dsw-static-other-world-focus)',
  '--dsw-alias-scrollbar-hover-l2': 'var(--dsw-static-other-world-stitch)',
  '--dsw-alias-state-business-primary': 'var(--dsw-static-other-world-cyan)',
  '--dsw-alias-state-business-tertiary': 'var(--dsw-static-other-world-cyan-14)',
  '--dsw-alias-state-error-primary': 'var(--dsw-static-other-world-error)',
  '--dsw-alias-state-error-secondary': 'var(--dsw-static-other-world-error-secondary)',
  '--dsw-alias-state-success-primary': 'var(--dsw-static-other-world-success)',
  '--dsw-alias-state-success-secondary': 'var(--dsw-static-other-world-success-secondary)',
  '--dsw-alias-state-success-tertiary': 'var(--dsw-static-other-world-success-18)',
  '--dsw-alias-state-warn-label': 'var(--dsw-static-other-world-amber)',
  '--dsw-alias-state-warn-primary': 'var(--dsw-static-other-world-amber)',
  '--dsw-alias-state-warn-secondary': 'var(--dsw-static-other-world-amber-hover)',
  '--dsw-alias-state-warn-tertiary': 'var(--dsw-static-other-world-amber-16)',
  '--dsw-alias-toast-bg': 'var(--dsw-static-other-world-elevated)',
  '--dsw-alias-tooltip-bg': 'var(--dsw-static-other-world-elevated)',
  '--dsw-specific-bubble-highlight': 'var(--dsw-static-other-world-elevated)',
  '--dsw-specific-bubble': 'var(--dsw-static-other-world-raised)',
  '--dsw-specific-input-major': 'var(--dsw-static-other-world-raised)',
  '--dsw-specific-login-input': 'var(--dsw-static-other-world-surface)',
  '--dsw-specific-menu': 'var(--dsw-static-other-world-elevated)',
  '--dsw-specific-selector': 'var(--dsw-static-other-world-raised)',
  '--dsw-specific-sidebar-fill': 'var(--dsw-static-other-world-surface)',
  '--dsw-specific-sidebar-nav-item-active-accent': 'var(--dsw-static-other-world-orange-14)',
  '--dsw-specific-sidebar-nav-item-active': 'var(--dsw-static-other-world-raised)',
  '--dsw-specific-sidebar-nav-item-hover': 'var(--dsw-static-other-world-elevated)',
  '--dsw-specific-tip': 'var(--dsw-static-other-world-raised)',
})
